[package]
name = "day18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.22.0"
tokio = { version = "1.35.0", features = ["full"] }
tokio-test = "0.4.3"
